### ISSUE TITLE
SSR mode

### ISSUE THREAD

**Issue by Vincz** [jaredLunde/masonic#10]
Hey Jared! First of all, thank you for this lib. I have a react project depending heavily on `react-virtualized`, but I'll be more than happy to switch to your library instead as it seems lighter and cleaner.

I have a problem with SSR. If I disable javascript on my webpage, my items are not displayed. 
They do exist in the DOM, but there are in visibility hidden and they are all stacked in the top left corner as their position doesn't seem to be calculated.
Here is my code  :

```
<Masonry
            items={items}
            render={render}
            ssrWidth={1920}
            ssrHeight={1024}
            columnWidth={350}
            columnGutter={20}
        />
```

It feels like the inital calculation is not called. Any idea about this ? Is there a special way to handle SSR with your library ? 

Thanks !

**Comment by Vincz** [comment]
Also with SSR, I get this warning:

```
Warning: Expected server HTML to contain a matching <div> in <div>. 
    in div (created by MasonryScroller)
    in MasonryScroller (created by c)
    in c (created by App)
```

with a SSR code as simple as that:

```
import { Masonry } from 'masonic';

const App = () => {
    const items = [{ id: 1 }, { id: 2 }, { id: 3 }];
    return (
        <Masonry
            items={items}
            render={({ data }) => (
                <div style={{ border: '1px solid red', width: '200px', height: '300px' }}>
                    hello
                </div>
            )}
        />
    );
}
```

Any idea, where it could come from ?

**Comment by Vincz** [comment]
With SSR, I also get an error when the `ssrWidth` is different of the real windows width.
I get an bunch of errors like that : 

`react_devtools_backend.js:6 Warning: Prop `style` did not match. Server: "width:386px;z-index:-1000;visibility:hidden;position:absolute;writing-mode:horizontal-tb" Client: "width:318px;z-index:-1000;visibility:hidden;position:absolute;writing-mode:horizontal-tb" 
`
It's obviously because the size doesn't match. Any idea how we could handle this?

**Comment by jaredLunde** [comment]
Hi Vincent. In answer to your first question about visibility being hidden, the layout rendering happens in two phase: 

First, `useMasonic()` creates a batch of new items based upon the `height`, `columnCount`, and `itemHeightEstimate` properties. These are the `visibility: hidden` elements you're seeing in your output. The reason for this first step is we don't have any way of knowing what the dimensions of a given cell will be until we measure them, thus, we can't know which column to stick each cell into. This first phase is therefore our "measurement" phase.

The second phase is the layout phase. In this phase, we know the measurements and can reliably render the actual cells - great news!

There are a few issues with being able to enter the second phase on the server. For one, we don't have access to an `offsetHeight` property on our React elements because they aren't actual DOM nodes on the server. So we can't know the height of an individual cell and therefore we can't know the height of any of the columns being generated - big bummer. A second issue is that React's server renderer is very mediocre in that it can't call `useEffect()` or do `forceUpdate()` - things that would allow us to enter the second phase regardless.

Because of those issues, the best we can do with SSR is make our content Google-discoverable. So the goal of SSR rendering in this library is really to do that as opposed to creating a layout that is visible before our client-side JS loads. `ssrWidth` and `ssrHeight` properties are used to determine the batch size in the first phase. That is, we're using them to figure out how many cells we should prerender content into for Google and other search engines. This small feature actually takes us a step far beyond what `react-virtualized` does, because with `react-virtualized` you get no cells on the server and therefore nothing for Google to consume.

In answer to the second question about React complaining about mismatches - you can safely ignore this. As you've already figured out, this is because our SSR width/height are not the same as every browser window that opens a page containing the Masonry component. I wish there were a way to just silence it based upon that knowledge, but unfortunately there isn't right now. I believe that's something they are currently working on with their new server renderer.

So obviously this is a long list of things we can't do so far, which sucks. The only possible solution I know of that may work is using a library like [react-snap](https://github.com/stereobooster/react-snap) which uses [puppeteer](https://www.google.com/search?client=firefox-b-1-d&q=puppeteer) under the hood to pre-render pages. Whether or not you want to take it that far really depends on your project goals. Consider that even if you got the cells to display in the pre-render phase, there would be visible jank once the client-side JS loaded - because as we've talked about earlier the widths won't match. Some browsers are sending headers with the client browser dimensions now, but in that case you'd have to be pre-rendering for each request which is going to be very expensive and slow.

I hope this gives you an idea of the numerous challenges in SSR and how I'm at least trying to make the best of what we've got 😄

**Comment by Vincz** [comment]
Thank you @jaredLunde 
It answers all my questions in details. Thank you for taking the time to answer with all this details.
I think the hidden content will be ok as it is, indeed, google friendly. 
I really enjoy your library so far and will definitely use it on my project. 

Thanks again!

**Comment by jaredLunde** [comment]
Anytime! Happy to answer any future questions you have. Have a good evening.

**Comment by Vincz** [comment]
Hey @jaredLunde 
I was wondering, if it would be possible to add events when the phase 1 starts and ends, and same for the phase 2.
I would like to display a list of placeholders ... and remove them when the phase 2 starts. So with SSR, we could have this placeholders displayed until the layout phase starts.

**Comment by jaredLunde** [comment]
I like the idea conceptually, but as of the latest version phase 1 is forced into phase 2 immediately after phase 1 is rendered to the DOM so any placeholder would be short lived and possibly burden the overall rendering process. A better way would be to detect whether or not there was a `window` global (`typeof window === 'undefined'`) and include your placeholder on the server, but not the client.

**Comment by jaredLunde** [comment]
[See here](https://github.com/jaredLunde/masonic/blob/master/src/index.tsx#L149)

**Comment by Vincz** [comment]
Yes, you are right. Or I could just display my list of placeholders and remove it as soon as the component is mounted.
Thanks!
