### ISSUE TITLE
Adding CSS animations

### ISSUE THREAD

**Issue by danielmichaelni** [jaredLunde/masonic#11]
I've been trying to add some CSS animations to the items, but I've been noticing that the animations seem to be triggering multiple times when scrolling. Is there a way to make animations smoother?

Example with fade animation: https://codesandbox.io/s/masonic-example-8usft?file=/src/index.js

**Comment by jaredLunde** [comment]
Animating on entry like this is likely not possible. Masonic uses an interval tree for searching which cells should be rendered to the window in `O(log n + k)` time. The interval tree search does not guarantee insertion order due to how it is structured, so while you might:

```
Expect: "1,2,3,4,5,6,7,8,9,10"
You'll Receive: "2,4,3,7,5,9,1,6,10,8"
```

As new cells positions are added to the tree, the search result order may change each time as a result. React re-uses the element subtrees thanks to the `key` prop, but it doesn't sort them for obvious reasons. So when they are inserted into the DOM, they may be in a different order each time. There's really nothing I can do about that, because I can't sort them either without serious algorithmic complexity complications.
