### ISSUE TITLE
Unable to test children components

### ISSUE THREAD

**Issue by GiselaMD** [jaredLunde/masonic#15]
I don't know if I'm doing it right but I can't test components inside Masonry...
I used the lib example (https://codesandbox.io/s/0oyxozv75v) and I wasn't able to test the content inside Masonry component.

Here is the component, and I want to test if I have the Test Id called "Pipoca":
``` 
import React from 'react';
import { Masonry } from 'masonic';

const getFakeItems = (cur = 0) => {
  const fakeItems = [];
  for (let i = 20 * cur; i < cur * 20 + 20; i++)
    fakeItems.push({
      id: i,
      name: 'Pipoca',
      src:
        'https://cdn.pixabay.com/photo/2017/06/12/19/02/cat-2396473__480.jpg',
    });
  return fakeItems;
};
const items = getFakeItems();

const FakeCard = ({ data: { id, name, src } }) => (
  <div>
    <img alt="kitty" src={src} data-testid="Pipoca" />
    <span>{name}</span>
  </div>
);

const MasonicTest = () => {
  return (
    <main>
      <div>
        <Masonry
          // This contains the data for our grid items
          items={items}
          // Adds 8px of space between the grid cells
          columnGutter={8}
          // Sets the minimum column width to 172px
          columnWidth={172}
          // Pre-renders 5 windows worth of content
          overscanBy={5}
          render={FakeCard}
        />
      </div>
    </main>
  );
};

export default MasonicTest;
```

Here is my test using @testing-library/react:
```
it('Renders Masonry', () => {
  const { getByTestId } = render(<MasonicTest />);
  expect(getByTestId('Pipoca')).toBeInTheDocument();
});
```

The test output is this below, It doesn't render the content inside:

![image](https://user-images.githubusercontent.com/34191327/82470636-fa68c500-9a9b-11ea-8f82-cf56c4eb7481.png)

But running the react application I can see all the content inside:
![image](https://user-images.githubusercontent.com/34191327/82470758-1f5d3800-9a9c-11ea-9741-cc19d4abf6cc.png)

Is something wrong with the test? Or is there a bug or something?

**Desktop:**

- OS: windows 10
- Browser chrome
- Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Package.json info:
 "masonic": "3.0.5",
 "react": "16.12.0",
"@testing-library/jest-dom": "5.5.0",
    "@testing-library/react": "10.0.4",
"jest-environment-jsdom-sixteen": "1.0.3",

**My test script is:**
"test": "react-scripts test --env=jest-environment-jsdom-sixteen",

**Comment by jaredLunde** [comment]
It'd probably be a good idea for me to adding a "Testing" section to the docs and/or create a library without some testing utilities. I am on vacation until next Tuesday so this probably won't happen in the next couple of weeks. This library uses virtualization and Masonry layouts in general rely on multi-phase rendering in order to measurement before writing grid cells to the DOM. Those two facts make for a pretty complicated testing environment. But it's totally possible, as is apparent from the 96% test coverage of this library.

[There's a whole lot of robust examples here](https://github.com/jaredLunde/masonic/blob/master/src/index.test.tsx) using `jest` and `react-testing library`. [You can see grid cells in the snapshots.](https://github.com/jaredLunde/masonic/blob/master/src/__snapshots__/index.test.tsx.snap)

As to why your specific example isn't working it's hard to say without poking around myself, but there are numerous possibilities. There could be [no default window size](https://github.com/jaredLunde/masonic/blob/master/src/index.test.tsx#L723) in your test environment, no default scroll position, there are *certainly* [no dimensions on the cards](https://github.com/jaredLunde/masonic/blob/master/src/index.test.tsx#L22).

**Comment by jaredLunde** [comment]
The best advice I can give for now is try to lift the utilities you need from the tests I linked to. As I said, these types of components are very difficult to test. I'd also encourage you *not* to test anything that is already tested by the library itself (cells changing when the scroll position or window size changes, etc.). I'm already doing that for you 😄
