### ISSUE TITLE
Newly loaded items from infiniteLoader seem to be placed in 1 column

### ISSUE THREAD

**Issue by PaulMyhr** [jaredLunde/masonic#17]
**Describe the bug**
Not sure if this is a bug or if I'm doing something incorrectly when using the useInfiniteLoader hook. But when I add new items that are loaded from the hook to the items array, it seems to place the new items all in one column most of the time instead of spreading them between columns based on their current height. Have you ever noticed this happening?

Wasn't able to recreate it in your codeSandbox so may be just how I'm using the component as well.

**Comment by jaredLunde** [comment]
This can only happen if you are using 100% dynamic/lazy measurement and the initial measurement yields heights that are small enough to fit all of the new items into the current shortest column. So if the shortest column is 150px shorter than the other columns, and the initial measurement for say, 10 new items, yields an avg <= 15px, all of those new cells will enter the shortest column. For this reason it's a good idea to do things like:
- Set a minimum height on your cell
- Load any images with `width` and `height` properties set. This can be determined easily if you know the width of your image because Masonic provides you the column width as a prop. So you'd just
```js
const MyCard = ({width, data: {image}}) => {
   return <img width={(image.width / width) * imgWidth} height={(image.width / width) * image.height}/>
}
```

I've personally never encountered this case, but I am obviously well aware of how the positioner works 😄 You can see the algorithm for column selection [here](https://github.com/jaredLunde/masonic/blob/master/src/index.tsx#L991)

It finds the shortest column, adds the new cell height to the height of that column, and repeats that for each new item added to the positioner. So if it consistently finds that the same column is the shortest one, it will keep using that.

**Comment by PaulMyhr** [comment]
Thanks for the reply - that was exactly it, didn't realize at what point it sized my cards. The min-height solved it though thanks
