### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by arnaudjnn** [jaredLunde/masonic#22]
Is it possible to add responsive on some props like ```<Masonry columnCount={[1, 1, 4, 5]} />``` ?

Do you need help on this?

**Comment by jaredLunde** [comment]
The grid already updates its column count automatically when using `columnWidth` instead of  `columnCount` so I don't see this happening. Plus it would require configuration on the user side as to what the breakpoints were and there's just no way I'm going to do that. Additionally, this can already be accomplished in user space if you really want to do it using a [`useMediaQueries()`](https://github.com/jaredLunde/react-hook/tree/master/packages/media-query#readme) hook to determine which column count to use.
