### ISSUE TITLE
Masnoic crashed when deleting items

### ISSUE THREAD

**Issue by JhonJohnatan** [jaredLunde/masonic#52]
**Describe the bug**
After deleting Items from masonic data, it crashes

**To Reproduce**

1. Fetch masonic 100 items
2. Delete 20 items
3. Refresh the page
4. See error (blank page)

**Expected behavior**
Masonic will support deleting items

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 83

**Additional context**
I tried the latest version, it still crashes

```
Uncaught Error: no data was found at index: 3
This ususally happens when you've mutate the "items" array in a way that makes it shorted than the previous "items" array...
```

**Comment by jaredLunde** [comment]
Read the error message, friend 🤦‍♂️

**Comment by JhonJohnatan** [comment]
Hey. I know the reason. Isn't there a way to support deleting? I have to mutate my items (filering..) @jaredLunde

**Comment by jaredLunde** [comment]
Show a placeholder when something is deleted instead of removing it from the array or use the `usePositioner()` hook with items as a dependency: https://codesandbox.io/embed/masonic-w-react-router-and-advanced-config-example-8em42?file=/src/index.js&codemirror=1

There aren't algorithmically-sound ways to support this in the library for all cases by default, hence you cannot do it. When you need it, you have to dig into the advanced API.

**Comment by JhonJohnatan** [comment]
Great man. thanks!

**Comment by em** [comment]
I'm finding that using usePositioner dependencies causes scrollTop to be lost - I believe the height shrinks to 0 as it is recalculating and it renders and it only works the codesandbox because the height estimator is kicking in. That's unreliable though.
