### ISSUE TITLE
Invalid ARIA role name

### ISSUE THREAD

**Issue by saj96n** [jaredLunde/masonic#59]
## Describe the bug
Hello Jared,
`griditem` is not valid name for a role of grid item component.

According to the [specification](https://www.w3.org/TR/wai-aria-1.1/#grid) it should be `gridcell`

**Comment by benpender** [comment]
Thanks for your work @jaredLunde .  +1 to this, seems an easy fix.  It would also be great if there was an easy way to set the tabIndex so this was more accessible.

**Comment by jaredLunde** [comment]
It's inside an interactive element (`grid`). It's my understanding that you shouldn't need a `tabIndex` on the individual cells (when the roles are correct). Also that could lead to a bad experience, because there's no clean way to bypass of the virtualization, which could go on infinitely. I will put out a fix for this soon.

**Comment by benpender** [comment]
@jaredLunde Thanks for getting back to me.  

"Also that could lead to a bad experience, because there's no clean way to bypass of the virtualization, which could go on infinitely."

I'm not sure what you mean here.  I was hoping to get the performance boost w/ virtualization but accessibility needs to work.  If I do useMasonic with itemAs: "button" I do get the tabbing behavior.  However it seems the first element in the grid is actually the last one in the html so pressing tab goes to the last one first.  This is why I think we need tab index.  I see you have a tabIndex prop for the container but not the items.  Does it just not work to have infinite scroll + virtualized tab indexes? 

I'm just diving into this stuff but It seems like there needs to be more logic here to enable that.  That way I'm guessing there's a way to continue with the tab index count when you render more elements as well. 

![Screen Shot 2021-01-21 at 4 58 32 PM](https://user-images.githubusercontent.com/1417152/105431433-7195c080-5c0a-11eb-8135-7fb74e120647.png)

**Comment by jaredLunde** [comment]
Closing this as I've fixed the specific issue in the latest release, but I am working on improving the accessibility beyond this, as well.
