### ISSUE TITLE
Can I turn off lazy loading widgets and load all regardless of whether they're in view?

### ISSUE THREAD

**Issue by chadsteele** [jaredLunde/masonic#6]
Great tool, but it get's clunky when the contents size changes on lazy load in view.  For example, I'm using it to arrange twitter widgets with dynamic sizes.  See
https://chadsteele-slync-twitter-client.netlify.app/

**Comment by jaredLunde** [comment]
Unfortunately I can't get this to load correctly so I don't fully understand the problem. But, I just released a new major with a bunch of bug fixes and performance enhancements that could possibly took care of this.

**Comment by chadsteele** [comment]
Works in chrome, but yes, degrades in other browsers and phones.  The issue is that several of the twitter widgets load after masonic "thinks" it's calculations are complete.  It would be nice if there was a hook or an event we can call that will trigger masonic to re-assess and re-organize

**Comment by jaredLunde** [comment]
You can force Masonic to reposition itself with the [`usePositioner()`](https://github.com/jaredLunde/masonic#usepositioneroptions-deps) hook and implement your own positioning hook with the [`createPositioner()`](https://github.com/jaredLunde/masonic#createpositionercolumncount-columnwidth-columngutter) utility. Yours is an advanced case and so you will be forced to use advanced features to accomplish it. If Masonic triggered a complete reflow on its own each time a cell updated it would be catastrophic to user experience. So it does the algorithmically reasonable thing and keeps the cell in place, updates the column sizes in its positioner cache, and as a result of that updates which column should receive the next cells when new ones are added. This is, in fact, the documented behavior. 

Re: Masonic loading "degrading in phones and browsers" - no. Masonic isn't degrading the experience, loading several iframes at a time in the browser is degrading the experience. This would be true no matter what layout algorithm you selected for windowing. That's why services like Twitter and Facebook don't actually load video elements, Spotify embeds, etc. in phone browsers until after a user opts in to viewing them by clicking.

**Comment by chadsteele** [comment]
I'm sorry if this sounds like criticism.  It is not.  Great tool!
I was just trying to clarify the behvior when combined with twitter widgets.
Thanks for the help!
