### ISSUE TITLE
Components rendering twice

### ISSUE THREAD

**Issue by danielmichaelni** [jaredLunde/masonic#7]
Thanks for the great library. I noticed that all my components are rendering twice on the initial load. Is there any way to get around this or is that intended? This is a problem for me because I want to use CSS animations, but they end up getting triggered twice.

**Comment by jaredLunde** [comment]
Unfortunately it has to happen that way due to the measuring and layout algorithm. The components need to be measured on the first mount. This measurement *has* to happen because we need to know if we should load a second batch of components. It's also used for positioning. The second phase is where the layout actually occurs.

**Comment by jaredLunde** [comment]
Phase one batching: https://github.com/jaredLunde/masonic/blob/master/src/index.tsx#L702
Phase two layout: https://github.com/jaredLunde/masonic/blob/master/src/index.tsx#L659

**Comment by danielmichaelni** [comment]
Got it. Thanks for the explanation!

**Comment by zernie** [comment]
Does it re-mount the components or render them twice?
