### ISSUE TITLE
Cat images overlap on the demo

### ISSUE THREAD

**Issue by chenxiaoyao6228** [jaredLunde/masonic#85]
**Describe the bug**
Cat images overlap on the demo

**To Reproduce**
see: https://codesandbox.io/s/masonic-inside-of-a-scrollable-div-example-k9l6c?file=/src/index.js

**Expected behavior**
expect not to overlap

**Screenshots**
![image](https://user-images.githubusercontent.com/29484219/127075005-ecb0a3b5-7ea2-47a0-828b-7da7710c78cd.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Braweria** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/62669899/129346340-8b605da1-1f58-4616-acf0-9908c94433ac.png)

I am on Desktop, Windows 10, Vivaldi (Chromium) Browser.

**Comment by samwyzz** [comment]
Facing a similar behavior.

Not to mention on the initial render of the masonry grid, all cells that could be fit inside the window are not displayed. Only upon scrolling do the cells get appended. Also these appended cells have a different vertical gap than the cells that are displayed on the initial render. 

Based on my limited understanding, and not knowing how to fix this, I believe this behavior is related to the itemHeightEstimate attribute. 

This is a confusing aspect of this package, since the whole purpose of masonry layouts is to have cells of varying heights and not having a single universal height.

I don't understand how a generalized height estimate could apply to cells with a major difference in height. For example a grid with some cells with a height of a say 1000px and some with a height of 50px. What would be the heightEstimate in this case ?

Reading the documentation I can not find any example of how the height of cells is calculated or if possible to provide a height per cell in case the height/aspect ratio of each cell is known before hand. 

Any help would be greatly appreciated.
